### ISSUE TITLE
收藏，有空看

### ISSUE THREAD

**Issue by Houtx** [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven#2]

**Comment by fortitude001** [comment]
技术小白一枚。
请问，下载下来后，用eclipse打开后，发现没有java resource等文件夹，是怎么回事啊？
就是说想问下文件下载后，具体需要做什么操作，然后就可以变成一个正常的java web项目了？

**Comment by Houtx** [comment]
没用过eclipse，这个项目支持myeclipes（可能需要手动选取lib中的jar）




------------------ 原始邮件 ------------------
发件人: "fortitude001"<notifications@github.com>;
发送时间: 2018年3月19日(星期一) 下午4:57
收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>;
抄送: "Hou"<97028415@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2)




技术小白一枚。
 请问，下载下来后，用eclipse打开后，发现没有java resource等文件夹，是怎么回事啊？
 就是说想问下文件下载后，具体需要做什么操作，然后就可以变成一个正常的java web项目了？

**Comment by humingliu** [comment]
别瞎教，不需要手动添加，eclipse安装一下maven插件，就行了。




------------------ 原始邮件 ------------------
发件人: "Htx"<notifications@github.com>;
发送时间: 2018年3月19日(星期一) 下午5:13
收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2)



没用过eclipse，这个项目支持myeclipes（可能需要手动选取lib中的jar） 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "fortitude001"<notifications@github.com>; 
 发送时间: 2018年3月19日(星期一) 下午4:57 
 收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>; 
 抄送: "Hou"<97028415@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2) 
 
 
 
 
 技术小白一枚。 
  请问，下载下来后，用eclipse打开后，发现没有java resource等文件夹，是怎么回事啊？ 
  就是说想问下文件下载后，具体需要做什么操作，然后就可以变成一个正常的java web项目了？

**Comment by Houtx** [comment]
不好意思，忘记是maven项目了，只想到了配置文件的问题，在idea中开发的可能Eclipse相关配置文件不会改变。




------------------ 原始邮件 ------------------
发件人: "humingliu"<notifications@github.com>;
发送时间: 2018年3月19日(星期一) 下午5:16
收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>;
抄送: "Hou"<97028415@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2)



别瞎教，不需要手动添加，eclipse安装一下maven插件，就行了。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Htx"<notifications@github.com>; 
 发送时间: 2018年3月19日(星期一) 下午5:13 
 收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2) 
 
 
 
 没用过eclipse，这个项目支持myeclipes（可能需要手动选取lib中的jar）  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "fortitude001"<notifications@github.com>;  
  发送时间: 2018年3月19日(星期一) 下午4:57  
  收件人: "HuangJunXiong/Spring-SpringMVC-MyBatis-Maven"<Spring-SpringMVC-MyBatis-Maven@noreply.github.com>;  
  抄送: "Hou"<97028415@qq.com>; "Author"<author@noreply.github.com>;   
  主题: Re: [HuangJunXiong/Spring-SpringMVC-MyBatis-Maven] 收藏，有空看 (#2)  
   
   
   
   
  技术小白一枚。  
   请问，下载下来后，用eclipse打开后，发现没有java resource等文件夹，是怎么回事啊？  
   就是说想问下文件下载后，具体需要做什么操作，然后就可以变成一个正常的java web项目了？

**Comment by Houtx** [comment]
我还以为问的是另一个demo项目。。。

**Comment by fortitude001** [comment]
嗯嗯，我问题已经解决了。非常感谢分享这么好的框架类程序！
